version: '2'
services:
  wiki_parser_python:
    build:
      context: ./../
      dockerfile: ./docker/python3.dockerfile
    image: python3:wiki_parser
    environment:
      PYTHONPATH: '$PYTHONPATH:/app/'
    links:
      - wiki_parser_mongodb
    volumes:
      - /home/ec/PycharmProjects/WebCrawler_FR:/app

  wiki_parser_mongodb:
    build:
      context: ./../
      dockerfile: ./docker/mongodb.dockerfile
    image: mongodb:wiki_parser
    volumes:
      - /home/ec/PycharmProjects/data/wiki_parser_mongodb:/data/db
    expose:
      - 27017