version: '2'
services:
  wiki_parser_python:
    build:
      context: ./../
      dockerfile: ./docker/python3.dockerfile
    image: python3:wiki_parser
    links:
      - wiki_parser_mongodb
    ports:
      - 5000:5000

  wiki_parser_mongodb:
    build:
      context: ./../
      dockerfile: ./docker/mongodb.dockerfile
    image: mongodb:wiki_parser
    volumes:
      - /project/storages/wiki_gmaps_parser_mongodb:/data/db
    expose:
      - 27017